### ISSUE TITLE
PermuteAdaptiveInstanceNorm2d ()

### ISSUE THREAD

**Issue by Sunshine19980919** [SY-Xuan/IIDS#1]
Hello, thank you for your excellent work.
I have a question: It seems that you have not defined PermuteAdaptiveInstanceNorm2d ()

![image](https://user-images.githubusercontent.com/81543547/190534643-803f5c20-8cad-468c-a3f3-28af75eae9be.png)

**Comment by SY-Xuan** [comment]
Oh, thanks for pointing that out. This is used for ablation studies. In the released version, I forgot to delete this part. I have fixed this part. Feel free to contact me if you still have any problems.
